#ifndef COUNTER_H_INCLUDED
#define COUNTER_H_INCLUDED

typedef struct counter_t;
typedef enum {
	MCLIBCOUNTER_ONESHOT,
	MCLIBCOUNTER_CONTINUOUES,
	MCLIBCOUNTER_BOUNCE,
	MCLIBCOUNTER_ILLEGALMODE
};


#endif // COUNTER_H_INCLUDED
